"""add_describe_column_on_news_table

Revision ID: 0ce6ed674378
Revises: 64bdeaa20f78
Create Date: 2024-01-08 05:31:25.968804

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0ce6ed674378'
down_revision = '64bdeaa20f78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('describe', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'describe')
    # ### end Alembic commands ###
