"""add_image_column_on_news_table

Revision ID: 64bdeaa20f78
Revises: b41a6e596c37
Create Date: 2024-01-07 14:45:04.596694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '64bdeaa20f78'
down_revision = 'b41a6e596c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image')
    # ### end Alembic commands ###
