"""update_category_table

Revision ID: b41a6e596c37
Revises: 0687357273fc
Create Date: 2024-01-05 15:43:56.908592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b41a6e596c37'
down_revision = '0687357273fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'image')
    # ### end Alembic commands ###
