"""update_order_table

Revision ID: bead1582fc8a
Revises: 386270ae1144
Create Date: 2024-01-03 16:30:09.661961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'bead1582fc8a'
down_revision = '386270ae1144'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tel', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=False))
    op.alter_column('orders', 'payments',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('orders', 'state',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'state',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('orders', 'payments',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'tel')
    # ### end Alembic commands ###
